import '../local_key.dart';
/// 中文简体
Map<String, String> hans = {
  'gexArchitecture':'GETX  架构',
  LanguageKey.loginTitle:'随时随地进行语言交流。',
  LanguageKey.loginSubTitle:'通过一次对话，认识世界。\n 接触新声音，探索新词汇。',
  LanguageKey.loginButtonApple:'苹果ID 登录',
  LanguageKey.loginButtonGoogle:'Google 登录',
  LanguageKey.loginButtonFb:'FaceBook 登录',
  LanguageKey.loginInfoNext:'下一步',
  LanguageKey.loginInfoDone:'完成',
  LanguageKey.loginInfoComplete:'完善个人信息',
  LanguageKey.loginInfoRecommendPartner:'为您推荐更好的语伴',
  LanguageKey.loginInfoBirthday:'生日',
  LanguageKey.loginInfoMale:'男',
  LanguageKey.loginInfoFeMale:'女',
  LanguageKey.loginInfoAgeAndSex:'年龄和性别填写后将不可更改哦~',
  LanguageKey.loginInfoIComeFrom:'我来自',
  LanguageKey.loginInfoNativeLan:'母语',
  LanguageKey.loginInfoLearnLan:'学习语言',
  LanguageKey.choose:'选择',
  LanguageKey.noteLan:'你来自的地区和母语填写后将不可更改~',
  LanguageKey.startStudy:'开始学习~',
  LanguageKey.nativeLan:'母语',
  LanguageKey.learnLan:'学习语言',
  LanguageKey.iComeFrom:'我来自',
  LanguageKey.countryChoose:'选择国家',
  LanguageKey.languageChoose:'学习语言',
  LanguageKey.started:'入门',
  LanguageKey.beginner:'初级',
  LanguageKey.intermediate:'中级',
  LanguageKey.advanced:'高级',
  LanguageKey.master:'精通',
};
