import '../local_key.dart';
/// 中文简体
Map<String, String> hans = {
  'gexArchitecture':'GETX  架构',
  LanguageKey.loginTitle:'随时随地进行语言交流。',
  LanguageKey.loginSubTitle:'通过一次对话，认识世界。\n 接触新声音，探索新词汇。',
  LanguageKey.loginButtonApple:'苹果ID 登录',
  LanguageKey.loginButtonGoogle:'Google 登录',
  LanguageKey.loginButtonFb:'FaceBook 登录',
  LanguageKey.login:'登 录',
  LanguageKey.loginButtonEmail:'邮箱',
  LanguageKey.loginInfoNext:'下一步',
  LanguageKey.loginInfoDone:'完成',
  LanguageKey.loginInfoComplete:'完善个人信息',
  LanguageKey.loginInfoRecommendPartner:'为您推荐更好的语伴',
  LanguageKey.loginInfoBirthday:'生日',
  LanguageKey.loginInfoMale:'男',
  LanguageKey.loginInfoFeMale:'女',
  LanguageKey.loginInfoAgeAndSex:'年龄和性别填写后将不可更改哦~',
  LanguageKey.loginInfoIComeFrom:'我来自',
  LanguageKey.loginInfoNativeLan:'母语',
  LanguageKey.loginInfoLearnLan:'学习语言',
  LanguageKey.choose:'选择',
  LanguageKey.noteLan:'你来自的地区和母语填写后将不可更改~',
  LanguageKey.startStudy:'开始学习~',
  LanguageKey.nativeLan:'母语',
  LanguageKey.learnLan:'学习语言',
  LanguageKey.iComeFrom:'我来自',
  LanguageKey.countryChoose:'选择国家',
  LanguageKey.languageChoose:'学习语言',
  LanguageKey.started:'入门',
  LanguageKey.beginner:'初级',
  LanguageKey.intermediate:'中级',
  LanguageKey.advanced:'高级',
  LanguageKey.master:'精通',
  LanguageKey.whatAreYouInto:'您喜欢什么？',
  LanguageKey.passwordHint:'请输入密码',
  LanguageKey.newPasswordHint:'请输入新密码',
  LanguageKey.confirmPasswordHint:'确认密码',
  LanguageKey.forgetPassword:'忘记密码?',
  LanguageKey.resetPassword:'重置密码',
  LanguageKey.password:'密码',
  LanguageKey.signUp:'注册',
  LanguageKey.registrationSuccessful:'注册成功',
  LanguageKey.registrationFailed:'注册失败',
  LanguageKey.email:'邮箱',
  LanguageKey.pleaseEnterYourEmail:'请输入邮箱',
  LanguageKey.sendVerificationCode:'发送验证码',
  LanguageKey.verificationCode:'验证码',
  LanguageKey.retrySendVerificationCode:'后重新获取',
  LanguageKey.verificationCodeFormatIncorrect:'验证码格式不正确',
  LanguageKey.passwordsAreInconsistent:'密码不一致',
  LanguageKey.emailFormatIsIncorrect:'邮箱格式不正确',
  LanguageKey.verificationCodeExpiredPleaseTryAgain:'验证码过期,请重新再试',
  LanguageKey.emailIsRegistered:'邮箱已注册',
  LanguageKey.resetPasswordSuccessful:'密码重置成功',
  LanguageKey.resetPasswordFailed:'密码重置失败',
};
