// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXwlGd1Ax792IhKgPb9l3NwrXCXhPZQ00',
    appId: '1:639803509344:web:18baae20f430a091335105',
    messagingSenderId: '639803509344',
    projectId: 'linguaexchange-7398f',
    authDomain: 'linguaexchange-7398f.firebaseapp.com',
    storageBucket: 'linguaexchange-7398f.appspot.com',
    measurementId: 'G-5SZEND3D2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFPZs9FyUHQuqtuKAbIMgfZhPjnZX_qo',
    appId: '1:639803509344:android:453e9769b829cdb7335105',
    messagingSenderId: '639803509344',
    projectId: 'linguaexchange-7398f',
    storageBucket: 'linguaexchange-7398f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjEgiTQtrX6FPlMsJbFGVz1dI6i7LZ44',
    appId: '1:639803509344:ios:788874f1dfd2f26f335105',
    messagingSenderId: '639803509344',
    projectId: 'linguaexchange-7398f',
    storageBucket: 'linguaexchange-7398f.appspot.com',
    iosBundleId: 'com.penny.liveChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjEgiTQtrX6FPlMsJbFGVz1dI6i7LZ44',
    appId: '1:639803509344:ios:788874f1dfd2f26f335105',
    messagingSenderId: '639803509344',
    projectId: 'linguaexchange-7398f',
    storageBucket: 'linguaexchange-7398f.appspot.com',
    iosBundleId: 'com.penny.liveChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwlGd1Ax792IhKgPb9l3NwrXCXhPZQ00',
    appId: '1:639803509344:web:7b5e27e9b4440cc3335105',
    messagingSenderId: '639803509344',
    projectId: 'linguaexchange-7398f',
    authDomain: 'linguaexchange-7398f.firebaseapp.com',
    storageBucket: 'linguaexchange-7398f.appspot.com',
    measurementId: 'G-RZQCLPK0KG',
  );
}
